### ISSUE TITLE
[Bug Report][3.1.1] Yarn Create Vuetify Fails for Windows User with Special Char in Username

### ISSUE THREAD

**Issue by peter-sidebotham** [vuetifyjs/create-vuetify#15]
### Environment
**Vuetify Version:** 3.1.1
**Vue Version:** 3.2.45
**Browsers:** Edge 108.0.1462.76
**OS:** Windows

### Steps to reproduce
1. Have an Azure joined Windows environment (optional): when a machine is azure joined, your home folder name is based on the display name of your O365 account.
2. Have a user display name containing parentheses e.g. "Peter Sidebotham (SIDM)" resulting in a home folder containing a parenthesis
3. Run "yarn create vuetify"

### Expected Behavior
Initialize a Vuetify 3 project

### Actual Behavior
Error: 'C:\Users\PeterSidebotham' is not recognized as an internal or external command,

### Reproduction Link
[https://codesandbox.io/s/boring-dust-1dty24](https://codesandbox.io/s/boring-dust-1dty24)

### Other comments
This appears to be a problem escaping the parenthesis character in the yarn command to initialize the vuetify 3 project. It's not clear to me if this is an issue with yarn or vuetify 3. I've tried the command in regular and elevated prompts, and in windows cmd and MinTTY. Given the oddness of having a parenthesis in a username, I would be happy with a more manual approach to initialize a project.

**Comment by KaelWD** [comment]
Is there a stack trace? What's the full home folder path you have? Is there any other terminal output?

**Comment by peter-sidebotham** [comment]
It looks like this is basically the same issue as [#10](https://github.com/vuetifyjs/create-vuetify/issues/10). There's not really a stack trace. The full home folder path is: C:\Users\PeterSidebotham(SIDM.
Yarn version is v1.22.19. Vuetify 3 documentation does not include any scaffold or install instructions except for "yarn create vuetify" so I have not tried alternative methods. 

Full terminal output is:
C:\SoftwareIDM\IdentityPanel\src\panel-ui>yarn create vuetify
yarn create v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...

success Installed "create-vuetify@1.0.6" with binaries:
      - create-vuetify
'C:\Users\PeterSidebotham' is not recognized as an internal or external command,
operable program or batch file.
error Command failed.
Exit code: 1
Command: C:\Users\PeterSidebotham(SIDM\AppData\Local\Yarn\bin\create-vuetify
Arguments:
Directory: C:\SoftwareIDM\IdentityPanel\src\panel-ui
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.

**Comment by KaelWD** [comment]
Yeah sounds like #10. I think we should switch the recommendation to npm or pnpm anyway.

**Comment by peter-sidebotham** [comment]
Sorry for the duplicate, I somehow missed 10. Elijah's comment got me to [Yarn issue 6851](https://github.com/yarnpkg/yarn/issues/6851). Espenja's solution to add a directory junction for my home folder and change the yarn cache and prefix directories worked for me. Thanks
