### ISSUE TITLE
Is layouts/ directory useful?

### ISSUE THREAD

**Issue by Glandos** [vuetifyjs/create-vuetify#16]
I've noticed the creation of `layouts/` directories with 2 Vue files, that are referenced in the router configuration.

However, they are not used, since the `main.ts` loads `App.vue` that doesn't do anything with either `<router-view />` nor those files in `layouts/` directory.

**Comment by istvank** [comment]
There is not even a `<router-view>` in your `App.vue`?
Is it this one? https://github.com/vuetifyjs/create-vuetify/blob/master/template/typescript/default/src/App.vue

Btw., as a newbie to Vuetify I was also a bit confused about the different directories for components, being `components`, `layouts`, and `views`. I couldn't find documentation about them anywhere. Seems like layouts are there for the greater, route-specific layout (cf. layouting system of Vuetify), views are for certain reusable UI patterns that you can use in multiple layouts, and components are for reusable, more fine-grained UI components.

**Comment by Glandos** [comment]
[**@istvank**](https://github.com/istvank) commented on [Jan 29, 2023, 3:19 PM GMT+1](https://github.com/vuetifyjs/create-vuetify/issues/16#issuecomment-1407676621 "2023-01-29T14:19:43Z - Replied by Github Reply Comments"):
> There is not even a `<router-view>` in your `App.vue`?  
No, as the template doesn't contain any.
> Is it this one? [`master`/template/typescript/default/src/App.vue](https://github.com/vuetifyjs/create-vuetify/blob/master/template/typescript/default/src/App.vue)
Yes.

> Btw., as a newbie to Vuetify I was also a bit confused about the different directories for components, being `components`, `layouts`, and `views`. I couldn't find documentation about them anywhere. Seems like layouts are there for the greater, route-specific layout (cf. layouting system of Vuetify), views are for certain reusable UI patterns that you can use in multiple layouts, and components are for reusable, more fine-grained UI components.

Those directories are just a "default" layout, they are not enforced anywhere. You can call them `dir1/`, `dir2/` and `tmp/` if you like your code as a mess :)

**Comment by johnleider** [comment]
We used to have README.md files for each directory but that seems to be gone for whatever reason.

**Comment by yanliang2004** [comment]
With unplugin-vue-router, routes are automatically created for pages in src/pages, without using any layouts. 
How are layouts and pages supposed to be used?

**Comment by johnleider** [comment]
Layouts are setup using https://github.com/JohnCampionJr/vite-plugin-vue-layouts which is compat with unplugin-vue-router. I believe this issue is outdated since it relates to an old version of the vuetify-create plugin.

**Comment by juw177** [comment]
The latest create vuetify uses vite-plugin-vue-layouts with unplugin-vue-router. All it does in practice is move the stuff that appears on every page, like the appbar, out into its own layouts/default.vue. Not worthwhile IMO as it can just go in /pages/index.vue or even App.vue.
