### ISSUE TITLE
Routing is broken in default generated version

### ISSUE THREAD

**Issue by kibertoad** [vuetifyjs/create-vuetify#18]
`<router-view>` is not present in default rendered view, so while routing will technically happen (no errors in console, address in addressbar changes), user won't see a different component rendered.
This is confusing for new users, one would assume enabling router preset should make routing work out-of-the-box.

**Comment by KaelWD** [comment]
Duplicate of #16

**Comment by kibertoad** [comment]
It's not exactly a duplicate. That ticket questions usefulness of `layouts` directory, while this one questions contents of the default view, when routing is enabled, because it's not really enabled.

**Comment by KaelWD** [comment]
Layouts isn't useful because routing isn't really used.
