### ISSUE TITLE
[Suggest] Add eslint-plugin-vuetify linter + [Deprecated] contain' has been replaced with 'cover'

### ISSUE THREAD

**Issue by scscgit** [vuetifyjs/create-vuetify#19]
The default project configuration might include a Vuetify-specific linter, which I accidentally found at https://github.com/vuetifyjs/eslint-plugin-vuetify and it's too sad that it isn't mentioned in official docs.
* _(This useful plugin is especially missing in Nuxt 3 setup; even the Nuxt 2's [create-nuxt-app](https://github.com/nuxt/create-nuxt-app) lacks it.)_

---

As a use-case to prove this point, [in HelloWorld.vue there](https://github.com/vuetifyjs/create-vuetify/blob/45444c8d87a73fd5636bcbb0666db92c842468f8/template/typescript/base/src/components/HelloWorld.vue#L5) is a deprecated prop usage, throwing the following build error
> .\src\components\HelloWorld.vue        
>   5:9  error  'contain' has been replaced with ['cover'](https://vuetifyjs.com/en/api/v-img/#props-cover)  vuetify/no-deprecated-props

(as long as `'plugin:vuetify/base'` is part of eslintrc.js. A `'plugin:vue/base'` doesn't seem to make any effect)

**Comment by KaelWD** [comment]
It's mentioned on https://vuetifyjs.com/en/getting-started/upgrade-guide/ and is only intended to be used while migrating from v2 to v3, some changes are ambiguous so will always show a warning.
