### ISSUE TITLE
Package dependency error with `npm install` command

### ISSUE THREAD

**Issue by shigeyf** [vuetifyjs/create-vuetify#23]
Encountered an errror about package dependency when creating a new vuetify app template with create-vuetify command.
The detailed procedure of the error reproduction is as follows.
If you will select "yarn" instead of "npm", then there is no error when executing `yarn install` command.
It's only a problem when using "npm" for installing dependencies.

> npm create vuetify

Vuetify.js - Material Component Framework for Vue

✔ Project name: … vuetify-project
✔ Which preset would you like to install? › Base (Vuetify, VueRouter) 
✔ Use TypeScript? … No / Yes
✔ Would you like to install dependencies with yarn, npm, or pnpm? › npm  <== Select "npm"

◌ Generating scaffold...
◌ Installing dependencies with npm...

vuetify-project has been generated at /home/shigeyf/dev/srcs/_working/shigeyf/dashboard/tmp/vuetify-project

Discord community: https://community.vuetifyjs.com
Github: https://github.com/vuetifyjs/vuetify
Support Vuetify: https://github.com/sponsors/johnleider

> cd vuetify-project
> npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: vuetify-project@0.0.0
npm ERR! Found: vite@4.3.8
npm ERR! node_modules/vite
npm ERR!   dev vite@"^4.2.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer vite@"^3.0.0" from @vitejs/plugin-vue@3.2.0
npm ERR! node_modules/@vitejs/plugin-vue
npm ERR!   dev @vitejs/plugin-vue@"^3.0.3" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by KaelWD** [comment]
#21
