### ISSUE TITLE
[Feature Request] Suggestion: Change wording in create-vuetify

### ISSUE THREAD

**Issue by ShizuhaAki** [vuetifyjs/create-vuetify#37]
### Problem to solve
Currently in create-vuetify, `Default` means the minimal install (with vuetify only), `Base` adds routing and `Essentials` adds some more. This is confusing because in many similar scenarios, `Base` and `Essential` are the minimal running preset , and `Default` is the developer recommended preset (which adds some tooling to make development easier).

### Proposed solution
The names should be changed. My proposal is:

- `Barebones` = the current `Default`,
- `Regular` = the current `Base`,
- `Extra` = the current `Essentials`.

**Comment by johnleider** [comment]
The naming convention is based off of eslint. The last remaining to do is "Recommended". Thank you for your suggestion.

**Comment by hdennen** [comment]
yes please. I just did this and was confused.

**Comment by johnleider** [comment]
Would it be better if there were only 2 options, default and recommended?

**Comment by hdennen** [comment]
I think the main confusion is whether detail has more or less than base or essentials. It is not immediately clear that default is less than base or essentials. The original proposal eliminates any ambiguity so I’d recommend that.
