### ISSUE TITLE
[Feature Request] "npm create vuetify" need update

### ISSUE THREAD

**Issue by softy2k** [vuetifyjs/create-vuetify#39]
### Problem to solve
Starting new project with cmd line : `npm create vuetify`, and manually selected no TypeScript, add Router, Pinia and ESLint, in **package.json** I have:
  ```
"devDependencies": {
    "@vitejs/plugin-vue": "^4.0.0",
    "eslint": "^8.22.0",
    "eslint-plugin-vue": "^9.3.0",
    "vite": "^4.2.0",
    "vite-plugin-vuetify": "^1.0.0"
  }
```

Still Vite 4 , not Vite 5.
If I 'force' update to vite-plugin-vuetify@2.0.1 I receive a lot of warnings. After that, project is starting OK.

Still, on '`npm run build`', I receive a warning: 
`The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.`

Tested on **Windows 10** with **NodeJS v18.19.0**

### Proposed solution
update `npm create vuetify`

**Comment by johnleider** [comment]
Just published a new update. Should be working properly now.
