### ISSUE TITLE
[Bug Report][3.5.2] "npm create vuetify" does not produce working project

### ISSUE THREAD

**Issue by carchrae** [vuetifyjs/create-vuetify#44]
### Environment
**Vuetify Version:** 3.5.2
**Vue Version:** 3.3.0
**Browsers:** Chrome 121.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
npm create vuetify
then choose 
- preset "Base"
- typescript "No"
- "npm"

### Expected Behavior
A working Hello World project

### Actual Behavior
fails to run.  

Error: The following dependencies are imported but could not be resolved:

  virtual:generated-layouts 

### Reproduction Link

- no link

### Other comments
This bug is in `npm create vuetify` - so, sorry about the bogus repro link.  I'm not sure how else to report this, but the dev experience of using the starter command and having an error is poor, so I presume is something you would care to know about.

https://github.com/vuetifyjs/create-vuetify/issues/16 - seems like it might be related.

**Comment by juw177** [comment]
It seems the new plugins are missing a bunch of tsconfigs and instructions

1. `"types": ["vite-plugin-vue-layouts/client", "unplugin-vue-router/client"]`
2. Need to include d.ts files in the root, not just /src
3. [unplugin-vue-router](https://github.com/posva/unplugin-vue-router/tree/main) requires us to first run npm run dev before npm run build. This is to generate the route types.

**Comment by johnleider** [comment]
This is resolved as of the latest release. Thank you for your patience.
