### ISSUE TITLE
[Bug Report][3.5.2] Get started with Vuetify 3 throws errors on npm run build

### ISSUE THREAD

**Issue by heziegl** [vuetifyjs/create-vuetify#45]
### Environment
**Vuetify Version:** 3.5.2
**Vue Version:** 3.4.15
**Browsers:** Chrome 121.0.0.0
**OS:** Windows 10

### Steps to reproduce
see readme.md:
* npm create vuetify
* select Essentials (Vuetify, VueRouter, Pinia)
* select Use TypeScript? Yes
* select npm
* npm install
* npm run build

I'm using Windows 10 and node v20.11.0

### Expected Behavior
build without errors

### Actual Behavior
Found 37 errors in 4 files.

### Reproduction Link
[https://github.com/heziegl/vuetify352_test](https://github.com/heziegl/vuetify352_test)

**Comment by juw177** [comment]
I have posted the cause here: https://github.com/vuetifyjs/create-vuetify/issues/44

**Comment by johnleider** [comment]
This is resolved as of the latest release.
